@BusinessManagementAPI_HostAddress = http://localhost:5176


### Get all orders
GET {{BusinessManagementAPI_HostAddress}}/api/orders
Accept: application/json

###Get all items from order
GET {{BusinessManagementAPI_HostAddress}}/api/orders/items

###Post new order
POST {{BusinessManagementAPI_HostAddress}}/api/orders
Content-Type: application/json

{
  "items": [
    {
      "productId": 3,
      "quantity": 2
    },
    {
      "productId": 4,
      "quantity": 1
    }
  ]
}

### Get all products
GET {{BusinessManagementAPI_HostAddress}}/api/products
Accept: application/json

###

### Get product by ID
GET {{BusinessManagementAPI_HostAddress}}/api/products/2
Accept: application/json

###

### Create a new product
POST {{BusinessManagementAPI_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "Red Velvet Cake",
  "description": "Red velvet cake with cream cheese frosting",
  "price": 500,
  "isActive": true
}

### test for model validation
POST {{BusinessManagementAPI_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "test",
  "description": "test",
  "price": 100,
  "isActive": true
}

### Update an existing product
PUT {{BusinessManagementAPI_HostAddress}}/api/products/3
Content-Type: application/json

{
  "id": 1,
  "name": "Chocolate Cake",
  "description": "Chocolate cake with vanilla filling",
  "price": 600,
  "isActive": true
}

### Delete a product
DELETE {{BusinessManagementAPI_HostAddress}}/api/products/1
